name: docker_deploy

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
      
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
        
permissions:
  contents: read

jobs:
  docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Create requirements file
        run: poetry export -f requirements.txt -o requirements.txt --without-hashes && cat requirements.txt
      - name: Get timestamp
        id: timestamp
        run: echo "TIME_STAMP=$(date +%s)" >> "$GITHUB_OUTPUT"
      - name: Build the Docker image
        env:
          TIME_STAMP: ${{ steps.timestamp.outputs.TIME_STAMP }}
        run: docker build . --file Dockerfile --tag afod3v/afobot:$TIME_STAMP
      - name: Login into DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Push into DockerHub
        env:
          TIME_STAMP: ${{ steps.timestamp.outputs.TIME_STAMP }}
        run: docker push afod3v/afobot:$TIME_STAMP
