name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"

jobs:

  docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install poetry dependencies
        run: poetry run poetry install
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag afod3v/afobot:${{ steps.timestamp.outputs.timestamp }}
      - name: Login into DockerHub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
      - name: Push into DockerHub
        run: docker push afod3v/afobot:${{ steps.timestamp.outputs.timestamp }}
