name: Integration

on:
  push:
    branches: [ "develope" ]

permissions:
  contents: read

jobs:
  Linter_Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install poetry dependencies
      run: poetry install
    - name: Check code with Black
      run: poetry run black .
      
  
  CI:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        poetry-version: ["1.0", "1.1.15", "latest"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install poetry dependencies
      run: poetry install
    - name: Poetry run pytest
      run: poetry run pytest
