name: railway_deploy

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
      
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
        
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Create requirements file
        run: poetry export -f requirements.txt -o requirements.txt --without-hashes && cat requirements.txt
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY }}
